"""
-----------------------------------------------------------------
(C) 2024 Prof. Tiran Dagan, FDU University. All rights reserved.
-----------------------------------------------------------------

Markdown Converter Script

This script converts a JSON file containing structured data (including text, tables, and images)
into a formatted Markdown file. It allows users to select a JSON file from a specified directory
and generates a corresponding Markdown file with properly formatted content.

Key features:
- Selects a JSON file from a specified output directory
- Converts various content types (Title, NarrativeText, ListItem, Table, Image) to Markdown format
- Handles base64-encoded images and includes them in the Markdown output
- Converts table data to Markdown-compatible format
- Preserves image summaries generated by the image summarizer script

Usage:
python 03_output_markdown.py

Dependencies:
- inquirer
- pandas
- tabulate

To install dependencies:
pip install inquirer pandas tabulate
"""

import json
import os
import inquirer
from tabulate import tabulate
import pandas as pd
from helpers.config import load_configuration, global_config

current_dir = os.path.dirname(os.path.abspath(__file__))

def select_json_file(directory):
    """
    Prompts the user to select a JSON file from the specified directory.

    Args:
        directory (str): The directory to search for JSON files.

    Returns:
        str: The full path of the selected JSON file, or None if no files are found.
    """
    json_dir = os.path.abspath(os.path.join(current_dir, directory))
    json_files = [f for f in os.listdir(json_dir) if f.endswith('.json')]
    if not json_files:
        print("No JSON files found in the output directory.")
        return None
    
    questions = [
        inquirer.List('file',
                      message="Select a JSON file to convert",
                      choices=json_files,
                      carousel=True)
    ]
    answers = inquirer.prompt(questions)
    return os.path.join(directory, answers['file'])

def convert_table_to_markdown(content):
    """
    Converts a table represented as a string to Markdown format.

    Args:
        content (str): A string representation of a list of lists containing table data.

    Returns:
        str: The table formatted in Markdown, or an error message if parsing fails.
    """
    try:
        # Assuming the content is a string representation of a list of lists
        table_data = eval(content)
        df = pd.DataFrame(table_data[1:], columns=table_data[0])
        return tabulate(df, headers='keys', tablefmt='pipe', showindex=False)
    except:
        return f"<Unable to parse table content: {content}>"

def json_to_markdown(json_data):
    """
    Converts JSON data to Markdown format.

    Args:
        json_data (list): A list of dictionaries containing structured content.

    Returns:
        str: The formatted Markdown content.
    """
    markdown_content = "\n"
    
    for item in json_data:
        category = item.get('type', 'Unknown')
        content = item.get('text', '')
        
        if category == 'Title':
            markdown_content += f"# {content}\n\n"
        elif category == 'NarrativeText':
            markdown_content += f"{content}\n\n"
        elif category == 'ListItem':
            markdown_content += f"- {content}\n"
        elif category == 'Table':
            markdown_content +=  item['metadata'].get('text_as_html', '') + "\n\n"           
        elif category == 'Image':
            image_base64 = item['metadata']['image_base64']
            if image_base64:
                # Determine the image format (assuming it's either PNG or JPEG)
                image_format = 'png' if image_base64.startswith('/9j/') else 'jpeg'
                summary = f"<p style=\"line-height:.9; bgcolor: #000\"><span style=\"font-family:Tahoma; font-size:.7em; color: #705\">{item['llm_summary']}</span></p>"
                image_tag = f"![IMAGE:](data:image/{image_format};base64,{image_base64})"
                markdown_content += f"| {image_tag}  |\n|:--:|\n| {summary} |\n\n"
            else:
                markdown_content += f"> Image: {content or '?Unknown'}\n\n"
        else:
            markdown_content += f"{content}\n\n"

    return markdown_content

def main():
    """
    Main function to run the JSON to Markdown conversion process.
    Handles file selection, conversion, and output.
    """
    if not load_configuration():
        return
    
    output_dir = os.path.realpath(global_config['DIRECTORIES']['OUTPUT_DIR'])
    json_file = select_json_file(output_dir)
    if not json_file:
        return
    
    with open(json_file, 'r', encoding='utf-8') as f:
        json_data = json.load(f)
    
    markdown_content = json_to_markdown(json_data)
    
    markdown_file = os.path.splitext(json_file)[0] + '.md'
    with open(markdown_file, 'w', encoding='utf-8') as f:
        f.write(markdown_content)
    
    print(f"Markdown file created: {markdown_file}")

if __name__ == "__main__":
    main()
